# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EAAES/assignments/pwm_generation/pwm_generation.srcs/sources_1/bd/pwm_generator_system/ip/pwm_generator_system_processing_system7_0_0/pwm_generator_system_processing_system7_0_0.xci
# IP: The module: 'pwm_generator_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EAAES/assignments/pwm_generation/pwm_generation.srcs/sources_1/bd/pwm_generator_system/ip/pwm_generator_system_processing_system7_0_0/pwm_generator_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_generator_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/EAAES/assignments/pwm_generation/pwm_generation.srcs/sources_1/bd/pwm_generator_system/ip/pwm_generator_system_processing_system7_0_0/pwm_generator_system_processing_system7_0_0.xci
# IP: The module: 'pwm_generator_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EAAES/assignments/pwm_generation/pwm_generation.srcs/sources_1/bd/pwm_generator_system/ip/pwm_generator_system_processing_system7_0_0/pwm_generator_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_generator_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
