# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/EAAES/assignments/pwm_generation/constraints.xdc

# Block Designs: bd/pwm_generator_system/pwm_generator_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system || ORIG_REF_NAME==pwm_generator_system}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_axi_gpio_0_0/pwm_generator_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_axi_gpio_0_0 || ORIG_REF_NAME==pwm_generator_system_axi_gpio_0_0}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_microblaze_0_axi_periph_0/pwm_generator_system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==pwm_generator_system_microblaze_0_axi_periph_0}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_xbar_1/pwm_generator_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_xbar_1 || ORIG_REF_NAME==pwm_generator_system_xbar_1}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_processing_system7_0_0/pwm_generator_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_processing_system7_0_0 || ORIG_REF_NAME==pwm_generator_system_processing_system7_0_0}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_rst_ps7_0_100M_0/pwm_generator_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==pwm_generator_system_rst_ps7_0_100M_0}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_modulator_axi_ip_0_0/pwm_generator_system_modulator_axi_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_modulator_axi_ip_0_0 || ORIG_REF_NAME==pwm_generator_system_modulator_axi_ip_0_0}]

# IP: bd/pwm_generator_system/ip/pwm_generator_system_auto_pc_0/pwm_generator_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_generator_system_auto_pc_0 || ORIG_REF_NAME==pwm_generator_system_auto_pc_0}]

# XDC: bd/pwm_generator_system/pwm_generator_system_ooc.xdc
